/**
 * Seed client_config from CSV data — run with: npx tsx scripts/seed-client-config.ts
 * Upserts CC/BCC contacts and reply templates for each client tag.
 */
import { createClient } from "@libsql/client";
import { config } from "dotenv";

config({ path: ".env.local" });

const db = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

interface ClientConfig {
  tag: string;
  reply_template: string;
  cc_name_1: string; cc_email_1: string;
  cc_name_2: string; cc_email_2: string;
  cc_name_3: string; cc_email_3: string;
  cc_name_4: string; cc_email_4: string;
  bcc_name_1: string; bcc_email_1: string;
  bcc_name_2: string; bcc_email_2: string;
}

// Parsed from the user-provided CSV. Tags with empty data are omitted.
const configs: ClientConfig[] = [
  {
    tag: "BAJFI",
    reply_template: `Hi {{first_name}},\nI'm CC'ing my bosses Rick and Chad since you're interested in {CONTEXT} for {{company_name}}.\nRick or Chad, can you please take it from here? Looks like a good number to call is {{phone_number}}.\nBest,\n{SENDER NAME}\nBay Area Janitorial Force\nOur Phone: (510) 575-7839 and (415) 206-1039`,
    cc_name_1: "Rick Davis", cc_email_1: "rick@bajfi.com",
    cc_name_2: "Chad Christian", cc_email_2: "customer-service@bajfi.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "SC",
    reply_template: `Hi {NAME},\nI'm CCing my main email and team since you're interested in hearing more about our Shockwave devices for {COMPANY NAME}.\nInternal note: number to call is {PHONE}\nShockwave Centers of America\nPhone: (561) 300-3444\nMarietta, GA 30068`,
    cc_name_1: "Shockwave Centers of America General", cc_email_1: "info@shockwavecenters.com",
    cc_name_2: "David Tucker", cc_email_2: "dtucker@shockwavecenters.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CWSJ",
    reply_template: `Hi {{first_name}},\nI'm CC'ing my bosses Vu and David since you're interested in {CONTEXT} for {{company_name}}.\nVu and David, can you please take it from here? Looks like a good number to call is {{phone_number}}.\nBest,\n{SENDER NAME}\nCity Wide San Jose\nOur Phone: (415) 316-3603`,
    cc_name_1: "Vu Le", cc_email_1: "Vu.Le@gocitywide.com",
    cc_name_2: "David Evan", cc_email_2: "devan@gocitywide.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "BBS",
    reply_template: `Hi {{first_name}},\nI'm CC'ing my bosses Jake and Nefi since you're interested in {CONTEXT} for {{company_name}}.\nJake or Nefi, can you please take it from here? Looks like a good number to call is {{phone_number}}.\nBest,\n{SENDER NAME}\nBluMont Building Services - Utah\nOur Phone: (801) 783-6923`,
    cc_name_1: "Jake Hamilton", cc_email_1: "jake@blumontservices.com",
    cc_name_2: "Nefi at BluMont Building Services", cc_email_2: "nefi@blumontservices.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "BTSB",
    reply_template: `Hi {FIRST_NAME},\nI'm CCing my bosses Jen and Adam since you're interested in closing auction deals faster with minimal work required on your end.\nJen and Adam, can you please take it from here? Looks like a good number to call is {PHONE_NUMBER}.\nBest,\n\n{SENDER_NAME}\nAshland Auction\nYou can reach us at: (407) 845-9021 & (407) 743-7472`,
    cc_name_1: "Jennifer Johnson", cc_email_1: "jen@trybtsb.com",
    cc_name_2: "Adam Field", cc_email_2: "adam@trybtsb.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "ABM",
    reply_template: `Hi {FIRST_NAME},\nI'm CC'ing my bosses Mollie and Dylan since you're interested in {CONTEXT} for {COMPANY}.\nMollie and Dylan, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n{SENDER NAME}\nAhlers Building Maintenance\nOur Phone: (913) 915-6740 and (913) 894-4440\nSchedule an appointment here: https://calendly.com/mollie-abmaintenance`,
    cc_name_1: "Mollie Estes", cc_email_1: "mollie@abmaintenance.com",
    cc_name_2: "Dylan at ABM", cc_email_2: "dylan@abmaintenance.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "IM",
    reply_template: `Hi {FIRST_NAME},\nI'm CC'ing my bosses Rob, Admir, and Abby since you're interested in {CONTEXT} for {COMPANY}.\nRob, Admir, or Abby, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n{SENDER NAME}\nIMC Janitorial Services LLC\nPhone for our Idaho office: (208) 760-5418`,
    cc_name_1: "Admir Susak", cc_email_1: "admir@imc.cleaning",
    cc_name_2: "Rob at Idaho Maintenance", cc_email_2: "rob@imc.cleaning",
    cc_name_3: "Admin at Idaho Maintenance", cc_email_3: "admin@imc.cleaning",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "FSD",
    reply_template: `Hi {FIRST_NAME},\nI'm CCing my boss to this email since you're interested in {CONTEXT}.\nEric, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n{SENDER NAME}\nForte of San Diego\nOur Phone: (619) 577-2104`,
    cc_name_1: "Eric Contreras", cc_email_1: "eric@fortecommercialcleaning.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "BHS",
    reply_template: `Hi {FIRST_NAME}\nI'm CCing my boss Cory to this email since you're interested in {CONTEXT} for {COMPANY}.\nCory, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n{SENDER NAME}\nNashville BHS\nNashville, TN 37204\nOur Phone: (615) 933-3913`,
    cc_name_1: "Cory Mitchell", cc_email_1: "cmitchell@nashvillebhs.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CI",
    reply_template: `Hi {FIRST_NAME},\nI'm CCing my colleague Allison to this email since you're interested in {CONTEXT} for {COMPANY}.\nAllison, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n{SENDER NAME}\nCappstone\nOur Phone: (415) 816-3574\n1501 Mariposa Street, Ste. 426\nSan Francisco, CA 94107`,
    cc_name_1: "Allison Pacatte", cc_email_1: "allison@cappstone.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Whitney Cook", bcc_email_1: "whit@cappstone.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CE",
    reply_template: `Hi {FIRST_NAME},\nDo you happen to know the approximate frequency of the service your interested in? (meaning monthly, weekly, or daily)\nAlso, I'm CCing my boss Cesar to this email since you're interested in {CONTEXT} for {COMPANY}.\nCesar, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n{SENDER NAME}\nCRISP Environments\nSan Diego, CA 92108\nPhone: (619) 513-7067`,
    cc_name_1: "Cesar Bustamante", cc_email_1: "cbustamante@crispenvironments.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Omar Lopez", bcc_email_1: "olopez@crispenvironments.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "SFS",
    reply_template: `Hi {FIRST_NAME},\nI'm CCing the executive partner of Summit Facility Solutions, Rocco Bove, to this email since you're interested in {CONTEXT} for {COMPANY}.\nSamantha, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n{SENDER NAME}\nSummit Facility Solutions\nServing New York and New Jersey Markets\nPhone: (800) 547-0116`,
    cc_name_1: "Rocco Bove", cc_email_1: "rocco@summitfacilitysolutions.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPC",
    reply_template: `Hi {FIRST_NAME},\nI'm CCing my boss Kim to this email since you're interested in {CONTEXT} for {COMPANY}.\nKim, can you please take it from here? Looks like a good number to call is {PHONE}.\nBest,\n\n{SENDER NAME}\nJan-Pro Greater Charlotte Region\nCharlotte, NC 28226\nPhone: (980) 280 6413`,
    cc_name_1: "Kim Blythe", cc_email_1: "Kim.Blythe@Jan-Pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "MTG",
    reply_template: `Hi {},\nI'm CC'ing Mony, Founder and CEO, as he personally does the walkthroughs so that we can send over the free quote for cleaning your space.\nMony or Tyler, can you please take it from here? Looks like a good number to call is {}\nBest,\n{SENDER NAME}\nMaid to Glow\nPhone: (678) 697-4679\n568 Versailles Dr Auburn, GA 30011`,
    cc_name_1: "Mony Gueorguiev", cc_email_1: "mony@maidtoglow.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Tyler Thebaut", bcc_email_1: "hello@maidtoglow.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "RFS",
    reply_template: `Hi {},\nI'm CCing Heather and our scheduling department to this email since you're interested in {CONTEXT} for {}.\nHeather and team, can you please take it from here? Looks like a good number to call is {}\nBest,\nRainier Facility Solutions\nPhone: (253) 327-3242\n823 Main Street, Ste. 2\nSumner, WA 98390`,
    cc_name_1: "Kyle Boyden", cc_email_1: "kyle@rainierfacilitysolutions.com",
    cc_name_2: "Heather Warren", cc_email_2: "hello@rainierfacilitysolutions.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPCI",
    reply_template: `Hi {},\nI'm CCing my bosses Diane and Kathleen to this email since you're interested in {CONTEXT} for {}.\nDiane or Kathleen, can you please take it from here? Looks like a good number to call is {}\nBest,\nJAN-PRO - Central Indiana\nPhone: (317) 472-1472\n8777 Purdue Road, Suite 121\nIndianapolis, IN 46268`,
    cc_name_1: "Diane Wilson", cc_email_1: "diane.wilson@jan-pro.com",
    cc_name_2: "Kathleen Singleton", cc_email_2: "ksingleton@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "IJSD",
    reply_template: `Hi {},\nI'm CCing my boss David to this email since you're interested in {CONTEXT} for {}.\nDavid, can you please take it from here? Looks like a good number to call is {}\nBest,\nIJS Dallas\nServicing the Greater Dallas/Fort Worth Metroplex\nPhone: (972) 215-7525\n3400 Coit Road Plano, Texas 75026`,
    cc_name_1: "David Davis", cc_email_1: "ddavis@ijsdallas.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPNNJ",
    reply_template: `Hi {},\nI'm CCing my bosses Lena and Gena to this email since you're interested in {CONTEXT} for {}.\nLena and Gena, can you please take it from here? Looks like a good number to call is {}\nBest,\n{SENDER NAME}\nJAN-PRO of Northern New Jersey\nPhone: (973) 276-1766\n142 Fairfield Rd Fairfield, NJ 07004`,
    cc_name_1: "Lena Alves", cc_email_1: "Lena.alves@jan-pro.com",
    cc_name_2: "Gena Kotarsky", cc_email_2: "Gena.kotarsky@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Jessica Carson", bcc_email_1: "jessica.carson@jan-pro.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPP",
    reply_template: `Hi {},\nI'm CCing my boss Andrew to this email since you're interested in {CONTEXT} for {}.\nAndrew, can you please take it from here? Looks like a good number to call is {}\nBest,\n{SENDER NAME}\nJAN-PRO of Philadelphia\nPhone: (610) 209-7589\nPhiladelphia 740 Springdale Dr, Ste 205\nExton, PA 19341`,
    cc_name_1: "Andrew Johnson", cc_email_1: "andrew.johnson@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPCKA",
    reply_template: `Hi {},\nI'm CCing my bosses Patrick and Bobby to this email since you're interested in {CONTEXT} for {}.\nPatrick and Bobby, can you please take it from here? Looks like a good number to call is {}\nBest,\n{SENDER NAME}\nJan-Pro Development of Columbus, Central GA and Auburn, AL\nO: 706-940-0220 (Columbus) | O: 478-259-7125 (Central GA)`,
    cc_name_1: "Patrick Gilbert", cc_email_1: "patrick.gilbert@jan-pro.com",
    cc_name_2: "Bobby Springer", cc_email_2: "bobby.springer@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Tonya Poe", bcc_email_1: "tonya.poe@jan-pro.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPDFW",
    reply_template: `Hi {},\nI'm CCing my boss Jacob to this email since you're interested in having a conversation about cleaning for {}.\nJacob, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Dallas/Fort Worth\nPhone: (214) 505-4117 or (214) 687-5500\n3000 Keller Springs Road, Suite 200\nCarrollton, TX 75006`,
    cc_name_1: "Jacob Merrill", cc_email_1: "jacob.merrill@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPK",
    reply_template: `Hi {},\nI'm CCing my bosses Michael and Jacob to this email since you're interested in having a conversation about cleaning for {}.\nMichael and Jacob, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Kentucky\nPhone: (502) 888-7030 or (502) 553-3859\n10170 Linn Station Road, Suite 500\nLouisville, KY 40223`,
    cc_name_1: "Michael Ray", cc_email_1: "michael.ray@jan-pro.com",
    cc_name_2: "Jacob Merrill", cc_email_2: "jacob.merrill@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "SCS",
    reply_template: `Hi {},\nI'm CCing my boss Ricardo to this email since you're interested in having a conversation about cleaning for {}.\nRicardo, can you please take it from here? Looks like a good number to call is {}.\nBest,\nSantana's Cleaning Service\nPhone: (408) 829-8059\nProudly servicing Bay Area commercial properties since 2000`,
    cc_name_1: "Ricardo Santana", cc_email_1: "ricardo@santanascleaningservice.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPSD",
    reply_template: `Hi {},\nI'm CCing my bosses Rick and Robin to this email since you're interested in having a conversation about cleaning for {}.\nRick or Robin, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO Commercial Cleaning San Diego\nPhone: (858) 210-6413\n4125 Sorrento Valley Blvd Ste E\nSan Diego, CA 92121`,
    cc_name_1: "Rick Canales", cc_email_1: "rick.canales@jan-pro.com",
    cc_name_2: "Robin Nelson", cc_email_2: "robin.nelson@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Keith Olmo", bcc_email_1: "keith.olmo@jan-pro.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "QP",
    reply_template: `Hi {},\nI'm CCing my team to this email to send over more details and potentially schedule a time to see how much we can save you from unnecessary processing fees from your POS at {}.\nJason and Blake, can you please take it from here? Looks like a good number to call is {}.\nBest,\nSkyTab\nOfficial Partner of Shift4 Payments in AZ & UT\nPhone: (866) 897-4096\nSchedule Appointment: https://www.skytabpro.io/schedule-a-demo`,
    cc_name_1: "SkyTab Team", cc_email_1: "team@skytabpro.io",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "EVC",
    reply_template: `Hi {FIRST_NAME},\n\nI'm CCing my boss, Justin, to this email since you're interested in {CONTEXT} for your space.\n\nJustin, can you please take it from here? Looks like a good number to call is {PHONE}.\n\nBest,\n\nEmerald Valley Cleaning\nPhone: (541) 225-7752\nEugene, OR`,
    cc_name_1: "Justin Aguirre", cc_email_1: "Info@emeraldvalleyclean.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "FCS",
    reply_template: `Hi {},\nI'm CCing my bosses Austin and Carlos to this email since you're interested in {CONTEXT} for {}.\nAustin and Carlos, can you please take it from here? Looks like a good number to call is {}.\nBest,\nFreedom Cleaning Solutions\nPhone: (407) 755-2967\n261 Live Oaks Blvd Bldg 6\nCasselberry, FL`,
    cc_name_1: "Austin Lasure", cc_email_1: "Austin@freedomcleaningsolutions.com",
    cc_name_2: "Carlos Mellizo", cc_email_2: "Carlos@freedomcleaningsolutions.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CPGH",
    reply_template: `Hi {},\nI'm CCing my bosses Jamie, Rochelle, and Serg to this email since you're interested in {CONTEXT} for {}.\nTeam, can you please take it from here? Looks like a good number to call is {}.\nBest,\nCleaning Pro Group\nPhone: (832) 600-6474 or (713) 304-5570\n2403 Washington St.\nWaller, TX, 77484`,
    cc_name_1: "Jamie Grubb", cc_email_1: "jamie.grubb@cleaningprogroup.com",
    cc_name_2: "Rochelle Lister", cc_email_2: "rochelle.l@cleaningprogroup.com",
    cc_name_3: "Sergiy Kozolup", cc_email_3: "serg.kozolup@cleaningprogroup.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CPGA",
    reply_template: `Hi {},\nI'm CCing my bosses Jeff, West, and Jamie to this email since you're interested in {CONTEXT} for {}.\nTeam, can you please take it from here? Looks like a good number to call is {}.\nBest,\nGlobal Maintenance Services Inc.\nPhone: (512) 346-4288\n1321 Rutherford Ln, Ste. 150\nAustin, TX 78753`,
    cc_name_1: "Jeff Lacy", cc_email_1: "jeff@gmaintenance.com",
    cc_name_2: "West Lacy", cc_email_2: "west@gmaintenance.com",
    cc_name_3: "Jamie Grubb", cc_email_3: "jamie.grubb@cleaningprogroup.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "DBSM",
    reply_template: `Hi {},\nI'm CCing my boss Sarah to this email since you're interested in {CONTEXT} for {}.\nSarah, can you please take it from here? Looks like a good number to call is {}.\nBest,\n\nDBS Building Solutions\nPhone: (866) 211-1288`,
    cc_name_1: "Sarah Garganese", cc_email_1: "sgarganese@dbsbuildingsolutions.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Scott Salvati", bcc_email_1: "ssalvati@dbsbuildingsolutions.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "DBSA",
    reply_template: `Hi {},\nI'm CCing my boss Sarah to this email since you're interested in {CONTEXT} for {}.\nSarah, can you please take it from here? Looks like a good number to call is {}.\nBest,\n\nDBS Building Solutions\nPhone: (866) 211-1288`,
    cc_name_1: "Sarah Garganese", cc_email_1: "sgarganese@dbsbuildingsolutions.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Scott Salvati", bcc_email_1: "ssalvati@dbsbuildingsolutions.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "DBSF",
    reply_template: `Hi {},\nI'm CCing my boss Xavier and Ray to this email since you're interested in having a conversation about cleaning for {}.\nXavier and Ray, can you please take it from here? Looks like a good number to call is {}.\nBest,\nDBS Building Solutions - Florida\n5118 N 56th St, Suite 206 Tampa, FL 33610\nPhone: (813) 666-4261`,
    cc_name_1: "Xavier Mendez", cc_email_1: "xmendez@dbsbuildingsolutions.com",
    cc_name_2: "Ray Gagliardi", cc_email_2: "rgagliardi@dbsbuildingsolutions.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Scott Salvati", bcc_email_1: "ssalvati@dbsbuildingsolutions.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "DBSNJ",
    reply_template: `Hi {},\nI'm CCing my boss Christine to this email since you're interested in having a conversation about cleaning for {}.\nChristine, can you please take it from here? Looks like a good number to call is {}.\nBest,\nDBS Building Solutions\nPhone: 866-211-1288\n379 Princeton Hightstown Rd bldg 1 suite e, East Windsor, NJ 08512`,
    cc_name_1: "Christine Miranda", cc_email_1: "njtm1@dbsbuildingsolutions.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Scott Salvati", bcc_email_1: "ssalvati@dbsbuildingsolutions.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "MPD",
    reply_template: `Hi {},\n\nI'm CCing my team to this email since you're interested in having a conversation about cleaning for {}.\n\nTeam, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nMaidPro Denver\nPhone: (303) 639-6100\n7808 Cherry Creek S Dr #101\nDenver, CO 80231`,
    cc_name_1: "Alyssa Smith", cc_email_1: "alyssasmith@maidpro.com",
    cc_name_2: "Lauren Guerrero", cc_email_2: "lguerrero@maidpro.com",
    cc_name_3: "Jaqueline Gonzalez", cc_email_3: "jgonzalez@maidpro.com",
    cc_name_4: "Ilse Torres", cc_email_4: "itorres@maidpro.com",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "SG",
    reply_template: `Hi {},\n\nI'm CCing my boss Norman to this email since you're interested in having a conversation about cleaning for {}.\n\nNorman, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nSpotless Group\nPhone: (845) 580-5200\nCommercial Cleaning Services Throughout The Tri-State Area`,
    cc_name_1: "Norman Lefkowitz", cc_email_1: "norman@spotlessgroupusa.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPH",
    reply_template: `Hi {},\nI'm CCing my bosses Renee and Anthony to this email since you're interested in having a conversation about cleaning for {}.\nRenee and Anthony, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Huntsville\nPhone: (205) 482-0305\n1101 McMurtrie Dr, Ste D2 Huntsville, AL`,
    cc_name_1: "Renee Eiland", cc_email_1: "renee.eiland@jan-pro.com",
    cc_name_2: "Anthony Gentile", cc_email_2: "anthony.gentile@jan-pro.com",
    cc_name_3: "Anthony Gentile (General)", cc_email_3: "aegentile2@gmail.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPLV",
    reply_template: `Hi {},\n\nI'm CCing my boss Steve to this email since you're interested in having a conversation about cleaning for {}.\n\nSteve, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Las Vegas\nPhone: (702) 952-1111\n1050 East Flamingo Rd, Ste N334\nLas Vegas, NV 89119`,
    cc_name_1: "Steve Rosen", cc_email_1: "steve.rosen@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "John Holthaus", bcc_email_1: "john.holthaus@janprocleans.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "RSC",
    reply_template: `Hi {},\n\nI'm CCing my boss Walter to this email since you're interested in having a conversation about cleaning for {}.\n\nWalter, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nRocket Science Cleaning\nPhone: (317) 967-2500\n8710 Bash St # 503323\nIndianapolis, IN 46256`,
    cc_name_1: "Walter Simpson", cc_email_1: "wsimpson@rocketsciencecleaning.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CSCC",
    reply_template: `Hi {FIRST_NAME},\n\nI'm CCing my bosses Cat and Ronique to this email since you're interested in {CONTEXT} for {COMPANY}.\n\nCat or Ronique, can you please take it from here? Looks like a good number to call is {PHONE}.\n\nBest,\n\nCivic Spark Cleaning Co.\nPhone: (516) 670-5171\n447 Broadway Fl 2\nNew York, NY, 10013`,
    cc_name_1: "Cat Capucino", cc_email_1: "civicsparkcleaning@gmail.com",
    cc_name_2: "Ronique Dixon", cc_email_2: "admin@civicsparkcleaning.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPET",
    reply_template: `Hi {},\nI'm CCing my bosses Lewis and Cheri to this email since you're interested in {CONTEXT} for {}.\nLewis and Cheri, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of East Tennessee\nPhone: (865) 333-0313\n1100 Marion St.Suite #301\nKnoxville, TN 37921`,
    cc_name_1: "Cheri Sanders", cc_email_1: "cheri.sanders@jan-pro.com",
    cc_name_2: "Lewis Craig", cc_email_2: "lewis.craig@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Melanie Holt", bcc_email_1: "Melanie.holt@jan-pro.com",
    bcc_name_2: "Bryan Lubaway", bcc_email_2: "bryan.lubaway@jan-pro.com",
  },
  {
    tag: "PC",
    reply_template: `Hi {},\nI'm CCing my bosses Kingsley and Michelle, to this email since you're interested in {CONTEXT} for {}.\nKingsley and Michelle, can you please take it from here? Looks like a good number to call is {}.\nBest,\nPriority Cleaning LLC\nPhone: (240) 665-0910\nServicing D.C., Maryland, and Virginia`,
    cc_name_1: "Kingsley Ofori", cc_email_1: "info@prioritycleaninginc.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPGW",
    reply_template: `Hi {},\n\nI'm CCing my boss Michael to this email since you're interested in having a conversation about cleaning for {}.\n\nMichael, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Greater Wichita\nPhone: (316) 761-9990\n3122 N Cypress Dr Ste 100\nWichita, KS 67226`,
    cc_name_1: "Michael Steinberg", cc_email_1: "michael.steinberg@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPWM",
    reply_template: `Hi {NAME},\n\nI'm CCing my boss Mackenzie to this email since you're interested in {CONTEXT} for {COMPANY}.\n\nMackenzie, can you please take it from here? Looks like a good number to call is {PHONE}.\n\nBest,\n\nJAN-PRO of West Michigan\nPhone: (616) 200-8690\n940 Monroe Ave NW Suite 136\nGrand Rapids, MI 49503`,
    cc_name_1: "WM Sales", cc_email_1: "wmsales@jan-pro.com",
    cc_name_2: "Mackenzie Holets", cc_email_2: "mackenzie.holets@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPU",
    reply_template: `Hi {},\n\nI'm CCing my bosses Brandyn and Ryan to this email since you're interested in having a conversation about cleaning for {}.\n\nBrandyn and Ryan, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Utah\nPhone: (801) 892-0110\n8238 S 700 E, Sandy, UT 84070`,
    cc_name_1: "Brandyn Paulsen", cc_email_1: "brandyn.paulsen@jan-pro.com",
    cc_name_2: "Ryan Richter", cc_email_2: "ryan.richter@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPOSW",
    reply_template: `Hi {},\nI'm CCing my bosses Tracy and Jennifer to this email since you're interested in having a conversation about cleaning for {}.\nTracy and Jennifer, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Oregon/SW Washington\nPhone: (503) 620-3881\n15714 SW 72nd Ave\nPortland, OR 97224`,
    cc_name_1: "Tracy Schweitzer", cc_email_1: "tracy.schweitzer@jan-pro.com",
    cc_name_2: "Jennifer Barajas", cc_email_2: "jennifer.barajas@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPSWM",
    reply_template: `Hi {},\nI'm CCing my boss Jose to this email since you're interested in having a conversation about cleaning for {}.\nJose, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Southwest Missouri\nPhone: 417-413-5631\n1985 West Hilltop Rd Ozark, MO 65721`,
    cc_name_1: "Jose Socorro", cc_email_1: "Jose.Socorro@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Nolen Hughes", bcc_email_1: "nolen.hughes@jan-pro.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPAR",
    reply_template: `Hi {},\nI'm CCing my boss Doug to this email since you're interested in having a conversation about cleaning for {}.\nDoug, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Central Arkansas\nPhone: (501) 907-9315\n9616 Maumelle Blvd, North Little Rock, AR 72113`,
    cc_name_1: "Doug Sternweis", cc_email_1: "douglas.Sternweis@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Nolen Hughes", bcc_email_1: "nolen.hughes@jan-pro.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CTS",
    reply_template: `Hi {},\n\nI'm CCing my bosses Aaron and Linda to this email since you're interested in having a conversation about cleaning for {}.\n\nAaron and Linda, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nCleanTech Services\nPhone: (215) 356-9876\n114 Chestnut St\nPhiladelphia, PA 19106`,
    cc_name_1: "Aaron Behrens", cc_email_1: "abehrens@coreassetmgmt.com",
    cc_name_2: "Linda Desiderio", cc_email_2: "ldesiderio@coreassetmgmt.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPCHI",
    reply_template: `Hi {},\n\nI'm CCing my bosses Gary, Patrick, and Angel to this email since you're interested in having a conversation about cleaning for {}.\n\nTeam, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Chicago\nPhone: (773) 245-0158\n136 Shore Dr, Burr Ridge, IL 60527`,
    cc_name_1: "Gary Ryndak", cc_email_1: "gary.ryndak@jan-pro.com",
    cc_name_2: "Angel Bello", cc_email_2: "angel.bello@jan-pro.com",
    cc_name_3: "Patrick Mooney", cc_email_3: "patrick.mooney@jan-pro.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Ted Asbury", bcc_email_1: "TedAsbury@thinkbigbrands.net",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPCIN",
    reply_template: `Hi {},\n\nI'm CCing my bosses Chris and Angel to this email since you're interested in having a conversation about cleaning for {}.\n\nChris and Angel, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Greater Cincinnati\nPhone: (513) 793-8000\n10250 Alliance Road, Suite 210\nCincinnati, OH 45242`,
    cc_name_1: "Chris McDonald", cc_email_1: "chris.mcdonald@jan-pro.com",
    cc_name_2: "Angel Bello", cc_email_2: "angel.bello@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Ted Asbury", bcc_email_1: "TedAsbury@thinkbigbrands.net",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPCNJ",
    reply_template: `Hi {},\n\nI'm CCing my bosses Tom and Jason to this email since you're interested in having a conversation about cleaning for {}.\n\nTom and Jason, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Central New Jersey\nPhone: (732) 738-5115\n1090 King Georges Post Rd #507, Edison, NJ 08837\nwww.jan-pro.com/centralnj`,
    cc_name_1: "Tom Weidemann", cc_email_1: "tom.weidemann@jan-pro.com",
    cc_name_2: "Jason Levy", cc_email_2: "jason.levy@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Manish Saini", bcc_email_1: "manish.saini@jan-pro.com",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "ECG",
    reply_template: `Hi {},\n\nI'm CCing my boss Joel to this email since you're interested in having a conversation about cleaning for {}.\n\nJoel, can you please take it from here? Looks like a good number to call is {}.\n\nEvergreen Cleaning Group\nPhone: (847) 846-8695\nBarrington & NW Chicago Suburbs, IL`,
    cc_name_1: "Joel Steven", cc_email_1: "Joel@evergreencleaninggroup.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPS",
    reply_template: `Hi {},\nI'm CCing my bosses Jocelyn and Sandeep to this email since you're interested in having a conversation about cleaning for {}.\nJocelyn and Sandeep, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Sacramento\n(916) 376-8977\n1355 Halyard Drive, Suite 150 West Sacramento, CA 95691`,
    cc_name_1: "Jocelyn Perez", cc_email_1: "Jocelyn.perez@jan-pro.com",
    cc_name_2: "Sandeep Kaur", cc_email_2: "sandeep.kaur@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "DO",
    reply_template: `Hi {},\n\nI'm CCing my bosses Cory and Kevin to this email since you're interested in having a conversation about cleaning for {}.\n\nCory and Kevin, can you please take it from here? Looks like a good number to call is {}.\nBest,\n\nDesert Oasis Commercial Cleaners\nPhone: 480-720-0907\n4600 E. Washington Suite 300\nPhoenix, Arizona 85034`,
    cc_name_1: "Cory Waltemath", cc_email_1: "cory@desertoasiscleaners.com",
    cc_name_2: "Kevin Waltemath", cc_email_2: "kevin@desertoasiscleaners.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPM",
    reply_template: `Hi {},\n\nI'm CCing my bosses Jason and Nicole to this email since you're interested in having a conversation about cleaning for {}.\n\nJason and Nicole, can you please take it from here? Looks like a good number to call is {}.\nBest,\n\nJAN-PRO of Memphis & The Mid-South\nPhone: (901) 457-4577 and (901) 683-4900\n7970 Courtyard Plaza Memphis, TN 38119`,
    cc_name_1: "Jason Pierami", cc_email_1: "jason.pierami@jan-pro.com",
    cc_name_2: "Nicole Clements", cc_email_2: "nicole.clements@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPCA",
    reply_template: `Hi {},\n\nI'm CCing my bosses Rhonda and Bailey to this email since you're interested in having a conversation about cleaning for {}.\n\nRhonda and Bailey, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Central & South Alabama\nPhone: 205-490-0418 and 205-767-7435\n234 Aquarius Drive Ste 106\nBirmingham, AL 35209`,
    cc_name_1: "Rhonda Gilbert", cc_email_1: "Rhonda.Gilbert@janprocleans.com",
    cc_name_2: "Bailey Gilbert", cc_email_2: "bailey.gilbert@janprocleans.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "BCSA",
    reply_template: `Hi {FIRST_NAME},\n\nI'm CCing my bosses Felipe, Eric, and Jose to this email since you're interested in {CONTEXT} for {COMPANY}.\n\nTeam, can you please take it from here? Looks like a good number to call is {PHONE}.\n\nBest,\n\n{SENDER NAME}\nBroomday Cleaning Services\nOur Phone: (512) 643-6854\n8911 North Capital of Texas Highway, Suite 4200 #1079 Austin, TX 78759`,
    cc_name_1: "Felipe Teran", cc_email_1: "felipe.teran@broomday.com",
    cc_name_2: "Eric Paz", cc_email_2: "eric.paz@broomday.com",
    cc_name_3: "Jose F. de Gracia", cc_email_3: "jose.degracia@broomday.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPNEGA",
    reply_template: `Hi {},\n\nI'm CCing my bosses Nichole, Angel, and Ryan to this email since you're interested in having a conversation about cleaning for {}.\n\nNichole, Angel, and Ryan, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Northeastern Georgia - Aiken\nPhone: (706) 834-8999 / (706) 426-7291\nAugusta Office: 105 Rossmore PL, Augusta, GA 30909\nAthens Office: 824 S Milledge Ave Suite 206, Athens, GA 30605`,
    cc_name_1: "Nichole Hayes", cc_email_1: "Nichole.hayes@jan-pro.com",
    cc_name_2: "Angel McMillan", cc_email_2: "Angel.mcmillan@jan-pro.com",
    cc_name_3: "Ryan Waldron", cc_email_3: "Ryan.waldron@jan-pro.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPCO",
    reply_template: `Hi {},\n\nI'm CCing my boss Dave to this email since you're interested in having a conversation about cleaning for {}.\n\nDave, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Colorado\nPhone: (720) 962-9060\n1720 S. Bellaire St. Suite 600\nDenver, CO 80222`,
    cc_name_1: "Dave Casey", cc_email_1: "dave.casey@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPSNE",
    reply_template: `Hi {},\n\nI'm CCing my bosses Kasey, Jon, and Tanya to this email since you're interested in having a conversation about cleaning for {}.\n\nKasey, Jon, and Tanya, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Southern New England\nPhone: (508) 963-8757, 401-317-0044, & (781) 367-2331\n3649 Post Road, 2nd Floor Warwick, RI 02886`,
    cc_name_1: "Kacey Henriques", cc_email_1: "kacey.henriques@jan-pro.com",
    cc_name_2: "Jon Winn", cc_email_2: "jon.winn@jan-pro.com",
    cc_name_3: "Tanya Oldham", cc_email_3: "tanya.oldham@jan-pro.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPT",
    reply_template: `Hi {},\nI'm CCing my bosses Makayla and Nick to this email since you're interested in having a conversation about cleaning for {}.\nMakayla and Nick, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of Greensboro (The Triad)\nPhone: (336) 510-5242 and (336) 822-9990\n11-B Oak Branch Dr Greensboro, NC 27407`,
    cc_name_1: "Nick Lane", cc_email_1: "nick.lane@jan-pro.com",
    cc_name_2: "Makayla Huber", cc_email_2: "makayla.huber@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPNW",
    reply_template: `Hi {},\nI'm CCing my bosses Alex and Charlie to this email since you're interested in having a conversation about cleaning for {}.\nAlex and Charlie, can you please take it from here? Looks like a good number to call is {}.\nJAN-PRO of Spokane & Coeur d'Alene\nPhone: (509) 534-9080 and (509) 979-6763\n104 South Freya Turquoise Flag Building, Suite 127 Spokane, WA 99202`,
    cc_name_1: "Alex Botezatu", cc_email_1: "Alex.Botezatu@jan-pro.com",
    cc_name_2: "Charlie Niemi", cc_email_2: "charlie.niemi@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "SH",
    reply_template: `Hi {},\nI'm CCing my boss Marcos to this email since you're interested in having a conversation about cleaning for {}.\nMarcos, can you please take it from here? Looks like a good number to call is {}.\nScrub Heroes\nPhone: (480) 356-9394\nPhoenix, AZ`,
    cc_name_1: "Marcos Yslas", cc_email_1: "ScrubHeroesContact@gmail.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CWSV",
    reply_template: `Hi {},\nI'm CCing our sales consultants to this email since you're interested in having a conversation about cleaning for {}.\nTeam, can you please take it from here? Looks like a good number to call is {}.\nBest,\nCity Wide Facility Solutions\nPhone: (650) 282-3559\n1601 El Camino Real, Suite 303\nBelmont, CA 94002`,
    cc_name_1: "Sales Consultants", cc_email_1: "siliconvalley-sales@gocitywide.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "VGM",
    reply_template: `Hi {},\n\nI'm CCing my bosses Michael and James to this email since you're interested in having a conversation about cleaning for {}.\n\nMichael and James, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nVanguard Cleaning Systems - Minnesota\nPhone: (651) 379-4000\n3459 Washington Drive, #109\nEagan, MN 55122`,
    cc_name_1: "Michael Hamerlind", cc_email_1: "mhamerlind@vgcsmn.com",
    cc_name_2: "James Nespbor", cc_email_2: "jnespbor@vgcsmn.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "RTWJ",
    reply_template: `Hi {},\n\nI'm CCing my bosses Eric and Paula to this email since you're interested in having a conversation about cleaning for {}.\n\nEric and Paula, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nRTW Janitorial\nrtwjanitorial.com\nPhone: (303) 437-2240`,
    cc_name_1: "Eric Bench", cc_email_1: "eric@rtwjanitorial.com",
    cc_name_2: "Paula Bench", cc_email_2: "paula@rtwjanitorial.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "KLCS",
    reply_template: `Hi {},\n\nI'm CCing my boss Kristopher and Lisa to this email since you're interested in having a conversation about cleaning for {}.\n\nKristopher and Lisa, can you please take it from here? Looks like a good number to call is {}.\n\nK&L Cleaning\nPhone: (432) 529-4325\n14218 West County Rd 177, Odessa, Texas 79766`,
    cc_name_1: "Kristopher Jackson", cc_email_1: "krisjackson@kandcleaningservicesapp.com",
    cc_name_2: "Lisa Jackson", cc_email_2: "lisajackson1321@knlcleaning.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "GJEC",
    reply_template: `Hi {},\n\nI'm CCing my boss Randy to this email since you're interested in having a conversation about cleaning for {}.\n\nRandy, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nElite Cleaning Service\nPhone: (970) 270-4129 and (760) 845-6889\nwww.elitecleaningcolorado.com\n560 S Commercial Dr Unit 1\nGrand Junction, CO 81505`,
    cc_name_1: "Randy Lesinski", cc_email_1: "randy@gjelitecleaning.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "PCL",
    reply_template: `Hi {},\n\nI'm CCing my boss Vernes to this email since you're interested in {context} for {}.\n\nVernes, can you please take it from here? Looks like a good number to call is {}.\n\nPremier Cleaning and Lawn LLC\nPhone: (605) 376 8895\n101 S Reid St Suite 307\nSioux Falls, SD 57103`,
    cc_name_1: "Vernes Otajagic", cc_email_1: "vernes@premiercleaningandlawn.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPNEP",
    reply_template: `Hi {},\n\nI'm CCing my teammates Joe, Rachael, and Mike to this email since you're interested in having a conversation about cleaning for {}.\n\nTeam, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of Northeastern PA\nPhone: (570) 824-1179 and (484) 224-3031\n94 Boston Hill Road\nLarksville, PA 18651`,
    cc_name_1: "Joe Bideganeta", cc_email_1: "Joe.bideganeta@jan-pro.com",
    cc_name_2: "Rachael Cochran", cc_email_2: "Rachael.Cochran@jan-pro.com",
    cc_name_3: "Mike Shutlock", cc_email_3: "Mike.Shutlock@jan-pro.com",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "GCJ",
    reply_template: `Hi {},\nI'm CCing my boss Mark and team to this email since you're interested in having a conversation about cleaning for {}.\nMark and team, can you please take it from here? Looks like a good number to call is {}.\nGreen Clean Janitorial\nPhone: 216-279-1929, 440-588-3858, 216-377-2393\n2580 E. 93rd St., Cleveland, OH 44104`,
    cc_name_1: "Mark Garcia", cc_email_1: "mgarcia@greencleanjanitorial.com",
    cc_name_2: "Sales at Green Clean Janitorial", cc_email_2: "Sales@greencleanjanitorial.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPNYC",
    reply_template: `Hi {},\nI'm looping in our field consultants Navil and Delilah to this email since you're interested in having a conversation about cleaning for {}.\nNavil and Delilah, can you please take it from here? Looks like a good number to call is {}.\nJAN-PRO of New York City\nPhone: (646) 705-0021\n14 E 60th Street, Suite 407 New York, NY 10022`,
    cc_name_1: "JAN-PRO of NYC Field Consultants", cc_email_1: "FieldConsultants.NYC@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "AFS",
    reply_template: `Hi {},\n\nI'm CCing my bosses David and Bryan to this email since you're interested in having a conversation about cleaning for {}.\n\nDavid and Bryan, can you please take it from here? Looks like a good number to call is {}.\n\nAbsolute Facility Solutions, Inc\nPhone: (714) 414-6763 and (714) 916-6232\n19744 Beach Blvd Suite 387\nHuntington Beach, CA 92648`,
    cc_name_1: "David Abdeen", cc_email_1: "david@absolutefsinc.com",
    cc_name_2: "Bryan Espinosa", cc_email_2: "Bryan@absolutefsinc.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPETC",
    reply_template: `Hi {},\n\nI'm CCing my bosses Lewis and Cheri to this email since you're interested in {CONTEXT} for {}.\n\nLewis and Cheri, can you please take it from here? Looks like a good number to call is {}.\n\nBest,\n\nJAN-PRO of East Tennessee\nPhone: (865) 333-0313\n1100 Marion St.Suite #301\nKnoxville, TN 37921`,
    cc_name_1: "Cheri Sanders", cc_email_1: "cheri.sanders@jan-pro.com",
    cc_name_2: "Lewis Craig", cc_email_2: "lewis.craig@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "Matt Connell", bcc_email_1: "matt.connell@jan-pro.com",
    bcc_name_2: "Bryan Lubaway", bcc_email_2: "bryan.lubaway@jan-pro.com",
  },
  {
    tag: "JPHO",
    reply_template: `Hi {},\nI'm CCing my boss Rick to this email since you're interested in having a conversation about cleaning for {}.\nRick, can you please take it from here? Looks like a good number to call is {}.\nJAN-PRO of Houston\nPhone: (281) 921-9000\n15810 Park Ten Place, Suite 135 Houston, TX 77084`,
    cc_name_1: "Rick Rostkowski", cc_email_1: "rick.rostkowski@jan-pro.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "NBM",
    reply_template: `Hi {},\nI'm CCing my boss Karl to this email since you're interested in having a conversation about cleaning for {}.\nKarl, can you please take it from here? Looks like a good number to call is {}.\nNorthwest Building Maintenance\nPhone: (509) 993-3398\n627 N Hogan Spokane, WA 99202`,
    cc_name_1: "Karl Bowen", cc_email_1: "kbowen@nwbminc.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "XTC",
    reply_template: `Hi {},\n\nI'm CCing my scheduling team to this email since you're interested in having a conversation about cleaning for {}.\n\nTeam, can you please take it from here? Looks like a good number to call is {}.\n\nXtreme Cleaning Las Vegas\nPhone: (702) 994-8343\nLas Vegas, NV & Surrounding Areas`,
    cc_name_1: "Xtreme Cleaning Las Vegas Team", cc_email_1: "sales@xtremecleaninglv.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "CS",
    reply_template: `Hi {},\nI'm CCing my boss Mike to this email since you're interested in having a conversation about cleaning for {}.\nMike, can you please take it from here? Looks like a good number to call is {}.\nThe Clean Start\nPhone: (253) 240-9592\n5009 Pacific Highway E, Ste 7, Fife, WA 98424`,
    cc_name_1: "Mike Stafford", cc_email_1: "mike@thecleanstart.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "PCC",
    reply_template: `Hi {},\nI'm CCing my boss Lane to this email since you're interested in having a conversation about cleaning for {}.\nLane, can you please take it from here? Looks like a good number to call is {}.\nBest,\nPhoenix Commercial Cleaning\nPhone: (480) 553-5248\n4750 S 44th Pl Suite 120 Phoenix, AZ 85040`,
    cc_name_1: "Lane Read", cc_email_1: "service@phxcommercialcleaning.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "JPNH",
    reply_template: `Hi {},\nI'm CCing my bosses Paulo and Leo to this email since you're interested in having a conversation about cleaning for {}.\nPaulo and Leo, can you please take it from here? Looks like a good number to call is {}.\nBest,\nJAN-PRO of New Hampshire\nPhone: (603) 595-0009\n39 Simon St, Unit #9\nNashua, NH 03060`,
    cc_name_1: "Paulo Moniz", cc_email_1: "Paulo.moniz@jan-pro.com",
    cc_name_2: "Leo Lorden", cc_email_2: "Leo.lorden@jan-pro.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "MS",
    reply_template: `Hi {},\nI'm CCing my bosses Amelia and Asher to this email since you're interested in having a conversation about cleaning for {}.\nAmelia and Asher, can you please take it from here? Looks like a good number to call is {}.\nBest,\nMetropoint Services\nPhone: 816-701-6885\n2300 Main Street, Suite 900, Kansas City, MO 64108`,
    cc_name_1: "Amelia Phillips", cc_email_1: "amelia@metropointservices.com",
    cc_name_2: "Asher Phillips", cc_email_2: "asher@metropointservices.com",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "OH",
    reply_template: `Thanks {FIRST_NAME},\n\nHere's a document explaining what we do with a few case studies: https://gamma.app/docs/OutboundHero-Commercial-Cleaning-Breakdown-zm5sgir0qsw3676\n\nI'm available:\n{Day 1}, {Month/Day} at {Time 1}, {Time 2}, {Time 3} PDT\n{Day 2}, {Month/Day} at {Time 1}, {Time 2}, {Time 3} PDT\n\nIf any of those times work for you, let me know.\nOtherwise, you can use my booking link if it's easier: https://calendly.com/d/cw8h-mc6-wgs/outbound-lead-generation-call\nLooking forward to connecting!\nOutboundHero\nPhone: (509) 800-7013`,
    cc_name_1: "", cc_email_1: "",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
  {
    tag: "TGS",
    reply_template: `Hi {},\nI'm CCing my boss Sam to this email since you're interested in {CONTEXT} for {}.\nSam, can you please take it from here? Looks like a good number to call is {}.\nBest,\n{SENDER NAME}\nTitan Global Solutions\n"Best way to hire vetted and qualified technical candidates"\nPhone: (510) 529-5396`,
    cc_name_1: "Sam Akhavi", cc_email_1: "sam.akhavi@tgsofficial.com",
    cc_name_2: "", cc_email_2: "",
    cc_name_3: "", cc_email_3: "",
    cc_name_4: "", cc_email_4: "",
    bcc_name_1: "", bcc_email_1: "",
    bcc_name_2: "", bcc_email_2: "",
  },
];

const UPSERT_SQL = `
  INSERT INTO client_config
    (client_tag, cc_name_1, cc_email_1, cc_name_2, cc_email_2,
     cc_name_3, cc_email_3, cc_name_4, cc_email_4,
     bcc_name_1, bcc_email_1, bcc_name_2, bcc_email_2,
     reply_template, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
  ON CONFLICT(client_tag) DO UPDATE SET
    cc_name_1 = excluded.cc_name_1,
    cc_email_1 = excluded.cc_email_1,
    cc_name_2 = excluded.cc_name_2,
    cc_email_2 = excluded.cc_email_2,
    cc_name_3 = excluded.cc_name_3,
    cc_email_3 = excluded.cc_email_3,
    cc_name_4 = excluded.cc_name_4,
    cc_email_4 = excluded.cc_email_4,
    bcc_name_1 = excluded.bcc_name_1,
    bcc_email_1 = excluded.bcc_email_1,
    bcc_name_2 = excluded.bcc_name_2,
    bcc_email_2 = excluded.bcc_email_2,
    reply_template = excluded.reply_template,
    updated_at = CURRENT_TIMESTAMP
`;

async function seedClientConfig() {
  console.log(`Seeding ${configs.length} client configs...`);

  let inserted = 0;
  for (const c of configs) {
    await db.execute({
      sql: UPSERT_SQL,
      args: [
        c.tag,
        c.cc_name_1 || null, c.cc_email_1 || null,
        c.cc_name_2 || null, c.cc_email_2 || null,
        c.cc_name_3 || null, c.cc_email_3 || null,
        c.cc_name_4 || null, c.cc_email_4 || null,
        c.bcc_name_1 || null, c.bcc_email_1 || null,
        c.bcc_name_2 || null, c.bcc_email_2 || null,
        c.reply_template || null,
      ],
    });
    inserted++;
  }

  console.log(`  Upserted ${inserted} configs.`);

  // Show sample
  const result = await db.execute(
    "SELECT client_tag, cc_email_1, cc_email_2, bcc_email_1 FROM client_config WHERE cc_email_1 IS NOT NULL ORDER BY client_tag LIMIT 10"
  );
  console.log("\nSample (first 10 with CC):");
  for (const row of result.rows) {
    const parts = [row.cc_email_1];
    if (row.cc_email_2) parts.push(row.cc_email_2 as string);
    if (row.bcc_email_1) parts.push(`BCC:${row.bcc_email_1}`);
    console.log(`  ${row.client_tag}: ${parts.join(", ")}`);
  }

  const total = await db.execute("SELECT COUNT(*) as n FROM client_config");
  console.log(`\nTotal client configs in DB: ${total.rows[0].n}`);
}

seedClientConfig().catch(console.error);
